site_name: Mai Bloom Docs

docs_dir: src
site_dir: docs

nav:
  - Home: index.md
  - urplans:
      - Overview: urplans/index.md
      - Setup: urplans/setup.md
      - Usage: urplans/usage.md
      - Architecture: urplans/architecture.md

theme:
  name: material
  logo: assets/images/logo.webp
  favicon: assets/images/favicon.ico
  palette:
    scheme: slate
    primary: "#3c0463"
    accent: "#fb5b14"
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.sections
    - search.highlight
    - toc.integrate

extra_css:
  - assets/css/overrides.css

markdown_extensions:
  - attr_list