site_name: Mai Bloom Docs
theme:
  name: material

docs_dir: src
site_dir: docs

nav:
  - Home: index.md
  - urplans:
      - Overview: urplans/index.md
      - Setup: urplans/setup.md
      - Usage: urplans/usage.md
      - Architecture: urplans/architecture.md
